[package]
name = "wre-transform"
version = "0.1.0"
authors = ["Bridger Herman <herma582@umn.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
